import { Inter } from "next/font/google";
import "./globals.css";
import { PasswordProvider } from "../context";
// import GlobalState from "../context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

<PasswordProvider>
  <main>
    {children}
  </main>
</PasswordProvider>

      </body>
    </html>
  )
}